name: Build and Test PR

on:
  pull_request:
      types: [ opened, edited, reopened, review_requested, synchronize ]
  workflow_dispatch:

env:
  app-name: "devops-k6-loadtest"
  rg-name: "rg-devops-k6-loadtest"
  slot-name: pr-${{ github.event.number }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore dotnet packages
        run: dotnet restore ./src/TestApi/TestApi.csproj

      - name: Build with dotnet
        run: dotnet build ./src/TestApi/TestApi.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish ./src/TestApi/TestApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/loadtestapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/loadtestapi

  deploy:
    runs-on: ubuntu-latest
    outputs:
      webapp-url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    needs: build
    environment:
      name: "PR"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AZ Account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az account set --subscription 956b7f52-f044-412c-a0ad-90e5aa93daf0
      
      - name: Create PR Slot
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az webapp deployment slot create --name ${{ env.app-name }} --resource-group ${{ env.rg-name }} --slot ${{ env.slot-name }} --subscription 956b7f52-f044-412c-a0ad-90e5aa93daf0

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-name }}
          slot-name: ${{ env.slot-name }}
          package: .

  loadtest:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - uses: actions/checkout@v2

      - name: Run LoadTests
        uses: k6io/action@v0.1
        with:
          filename: './src/LoadTests/loadtest.js'
          flags: -e MY_HOSTNAME=${{ needs.deploy.outputs.webapp-url }}
